//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class iletisim
    {
        public int iletisimID { get; set; }
        [Required(ErrorMessage = "Bos Geçilemez !")]
        public string yazi { get; set; }
        [Required(ErrorMessage = "Bos Geçilemez !")]
        public string adres { get; set; }
        [Required(ErrorMessage = "Bos Geçilemez !")]
        public string tel { get; set; }
        [Required(ErrorMessage = "Bos Geçilemez !")]
        public string harita { get; set; }
    }
}
