//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class yazarlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public yazarlar()
        {
            this.news = new HashSet<news>();
        }
    
        public int yazarID { get; set; }
        [Required(ErrorMessage = "Bos Geçilemez !")]
        public string adi { get; set; }
        [Required(ErrorMessage = "Bos Geçilemez !")]
        public string soyadi { get; set; }
        [Required(ErrorMessage = "Bos Geçilemez !")]
        public string mail { get; set; }
        [Required(ErrorMessage = "Bos Geçilemez !")]
        public string kullaniciAdi { get; set; }
        [Required(ErrorMessage = "Bos Geçilemez !")]
        public string sifre { get; set; }
        public string P_resim { get; set; }
        public bool yetki { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<news> news { get; set; }
    }
}
